### ISSUE TITLE
innewmarcs

### ISSUE THREAD

**Issue by fredifqh** [trevisanj/PFANT#16]
When I run innewmarcs I get thi next error

(INFO    ) :: read_main(): reading file 'main.dat'...
(INFO    ) :: read_moo(): reading file 'grid.moo'...
(HALTING ) :: read_moo(): (record #2) Number of depth layers must be 56, not 1073731179
STOP -1

**Comment by trevisanj** [comment]
Thank you for reporting this error. The problem was probably due to link to wrong file grid.moo in the README section 2.2. The link has been fixed.

Correct file (241 MB): https://docs.google.com/uc?export=download&confirm=4o6l&id=0B8m8GNLFiaewejd6dmJ6MW1pX2c

Please replace your PFANT/data/common/grid.moo with this file.

Note: the wrong grid.moo had only 203 MB.
